# Prometheus Operator YAML placeholder
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: monitoring
  namespace: monitoring
spec:
  targetNamespaces:
  - monitoring
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: prometheus-subscription
  namespace: monitoring
spec:
  channel: stable
  name: prometheus
  source: community-operators
  sourceNamespace: openshift-marketplace
